; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes
; RUN: opt -S < %s -gvn | FileCheck %s

@G1 = internal global i32 0

declare void @foo1a(i8* readnone nocapture, i8) local_unnamed_addr
declare void @foo1b(i8* nocapture, i8) local_unnamed_addr readnone
declare void @foo1c(i8* nocapture, i8) local_unnamed_addr inaccessiblememonly

; Doesn't read from pointer argument, promotable
define i32 @a() {
; CHECK-LABEL: define {{[^@]+}}@a()
; CHECK-NEXT:    store i32 42, i32* @G1
; CHECK-NEXT:    call void @foo1a(i8* bitcast (i32* @G1 to i8*), i8 0)
; CHECK-NEXT:    call void @foo1b(i8* bitcast (i32* @G1 to i8*), i8 0)
; CHECK-NEXT:    call void @foo1c(i8* bitcast (i32* @G1 to i8*), i8 0)
; CHECK-NEXT:    ret i32 42
;
  store i32 42, i32 *@G1
  %p = bitcast i32* @G1 to i8*
  call void @foo1a(i8* %p, i8 0)
  call void @foo1b(i8* %p, i8 0)
  call void @foo1c(i8* %p, i8 0)
  %a = load i32, i32* @G1
  ret i32 %a
}
